START python consumer.py 1
START python consumer.py 2
START python consumer.py 3
START python consumer.py 4
START python consumer.py 5
START python consumer.py 6
START python consumer.py 7
START python consumer.py 8
START python consumer.py 9
START python consumer.py 10 